### ISSUE TITLE
Question about getting the number of citations

### ISSUE THREAD

**Issue by zhtjtcz** [Future-Scholars/paperlib-citation-count-extension#1]
I found that the number of citations obtained using the extension sometimes differed from the number on Google Scholar.

And I tried to read the source code to find out why, but found that the number of citations was obtained using the API on the `https://api.paperlib.app`.

I wonder if the author has any plans to change this part of the code to use a public API? It doesn't seem necessary for users to access the server while getting citations.

Looking forward to the author's reply. Happy to discuss improvements to this extension.

**Comment by GeoffreyChen777** [comment]
Hi,

1. There is no Google Scholar API. And Google's anti-scraping policy is very strict.
2. We use SemanticScholar API. It requires API key. So I need to use our server to protect the API key.
